spring:
  profiles: neo4j
  neo4j.uri: bolt://neo4j:7687
  neo4j.database: test
  health:
    group:
      readiness.include: neo4j
  datasource:
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
    url: jdbc:neo4j:${spring.neo4j.uri}
    username: ${spring.neo4j.authentication.username}
    password: ${spring.neo4j.authentication.password}
  liquibase:
    enabled: true
    change-log: classpath:/database/neo4j/changes.xml