version: "2"

services:
  neoj4:
    image: neo4j:4.3.7
#    mem_limit: 500m
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      backend:
        aliases:
          - neo4j

networks:
  backend:
